### ISSUE TITLE
Request to write Xlf changes to a file

### ISSUE THREAD

**Issue by EricZwirnmann** [daniel-sc/ng-extract-i18n-merge#42]
I automate the build of the XLF files using this app.  Would like to have an output file that contains a list of changes that were made to the master and associated locale files.  yes, I can use PR to handle this, but that requires the developers to be responsible to run this in a script.  I currently use the build server run this app in a script and would like to validate that all translations strings are in the output locale files.  In addition be able to quickly see a list of new strings that need to be sent out for translation.

example:
Add an option called "changes":"yourfolder/outputfile.txt"

debug file would contain something like:
new    <sourcefile.xlf>  string
new    <message.es.xlf> string
deleted <sourcefile.xlf> string
updated <sourcefile.xlf> string

Any additional change information to the files is also acceptable.

**Comment by daniel-sc** [comment]
Hi @EricZwirnmann 

Regarding your primary requirement:

> validate that all translations strings are in the output locale files

Did you know that you can simply fail your Angular CLI build on missing translation strings: https://angular.io/guide/i18n-common-merge#report-missing-translations? I think this is the best way to handle this. If you think otherwise, please share some details :)

As for the additional requirement:

> quickly see a list of new strings that need to be sent out for translation

Here I'd indeed suggest that the PR is the correct place to immediately "see" new/updated translations. Furthermore you could filter on the `state` attribute of translation units (of course you should make sure that translated units correctly get an updated state, such as "final" or "translated" by the translator).

Please don't hesitate to reopen, if the suggestions seem not convincing for your situation!
